server.port=8080
spring.application.name=railsetu-operations

# Production MySQL Profile
spring.datasource.url=jdbc:mysql://localhost:3306/railsetudb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

railsetu.jwt.secret=RailSetuSuperSecretKeyForSigningJwtTokensRailwaysOperations2026SecureKey!
railsetu.jwt.expiration-ms=86400000
railsetu.inventory.seat-hold-timeout-minutes=10
railsetu.simulation.academic-dynamic-pricing-enabled=true
